FROM python:3.10-slim

WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

# Use Gunicorn as the web server for production
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]
